package com.auraos.collab_canvas

import com.highcapable.yukihookapi.YukiHookAPI
import com.highcapable.yukihookapi.annotation.xposed.InjectYukiHookWithXposed

/**
 * Xposed Module Entry Class
 * 
 * This class is automatically generated by YukiHookAPI.
 * Do not modify this class unless you know what you are doing.
 */
@InjectYukiHookWithXposed(
    isUsingResourcesHook = false, // Set to true if you need to hook resources
    isUsingXposedModuleLoader = true
)
object HookEntry : YukiHookAPI.HookEntry() {
    
    /**
     * Called when the module is initialized
     */
    override fun onInit() {
        // Configure your module's behavior here
        YukiHookAPI.config()
            .debuggable(BuildConfig.DEBUG) // Enable debugging in debug mode
            .isEnableModulePrefsCache = true // Enable module prefs cache
    }
    
    /**
     * Called when the module is loaded by Xposed
     */
    override fun onHook() {
        // Your hook logic will go here
        // Example:
        // loadApp("com.example.app") {
        //     // Hook methods here
        // }
    }
}
