[versions]
# ===== GRADLE & KOTLIN =====
agp = "8.2.2"
benchmarkJunit4 = "1.4.0"
kotlin = "1.9.20"
ksp = "1.9.20-1.0.14"
serialization = "1.9.0"
desugar_jdk_libs = "2.1.5"

# ===== HOOKING FRAMEWORKS =====
xposed = "82"
lsposed = "6.4"
yukihook = "1.3.0"
kavaref = "1.0.1"

# ===== GOOGLE & FIREBASE =====
hilt-version = "2.48"
gson-version = "2.13.1"
firebaseBom = "34.2.0"
espresso-core = "3.7.0"
# ===== ANDROIDX =====
coreKtx = "1.17.0"
appcompat = "1.7.1"
composeBom = "2025.08.01"
activityCompose = "1.10.1"
navigationCompose = "2.9.3"
lifecycle = "2.9.3"
roomVersion = "2.7.2"
hilt-navigation-compose-version = "1.2.0"

# ===== NETWORKING =====
retrofit = "3.0.0"
okhttp = "5.1.0"

# ===== UTILITIES =====
coilCompose = "2.7.0"
timber = "5.0.1"

# ===== BUILD PLUGINS =====
openapiGeneratorGradlePlugin = "7.15.0"
ktlint = "13.1.0"
detektGradlePlugin = "1.23.8"
dokkaGradlePlugin = "2.0.0"
spotlessPluginGradle = "7.2.1"

# ===== TESTING =====
junit = "4.13.2"
junitJupiter = "5.13.4"
androidxTestJunit = "1.3.0"
mockk = "1.14.5"
turbine = "1.2.1"
uiautomator = "2.3.0"

[plugins]
# ===== ANDROID =====
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

# ===== KOTLIN =====
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# ===== HILT =====
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-version" }

# ===== FIREBASE =====
google-services = { id = "com.google.gms.google-services", version = "4.4.3" }

# ===== CODE QUALITY & TOOLS =====
dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaGradlePlugin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotlessPluginGradle" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapiGeneratorGradlePlugin" }

[libraries]
# ===== YUKIHOOK & XPOSED =====
androidx-benchmark-junit4 = { module = "androidx.benchmark:benchmark-junit4", version.ref = "benchmarkJunit4" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
yukihook-api = { group = "com.highcapable.yukihookapi", name = "api", version.ref = "yukihook" }
yukihook-core = { group = "com.highcapable.yukihookapi", name = "api", version.ref = "yukihook" }
yukihook-ksp = { group = "com.highcapable.yukihookapi", name = "ksp-xposed", version.ref = "yukihook" }
# Note: yukihook-prefs is deprecated in 1.3.0+, replaced by KavaRef
kavaref-core = { group = "com.highcapable.kavaref", name = "kavaref-core", version.ref = "kavaref" }
kavaref-extension = { group = "com.highcapable.kavaref", name = "kavaref-extension", version.ref = "kavaref" }
xposed-api = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }

# ===== ANDROIDX CORE =====
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version = "1.13.0" }

# ===== COMPOSE =====
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# ===== LIFECYCLE =====
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }

# ===== ROOM =====
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }

# ===== HILT =====
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-version" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt-version" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt-version" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose-version" }


# ===== FIREBASE =====
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-perf-ktx = { group = "com.google.firebase", name = "firebase-perf-ktx" }

# ===== NETWORKING =====
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-kotlinx-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

# ===== KOTLINX =====
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.10.2" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version = "1.10.2" }

# ===== UTILITIES =====
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson-version" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }

# ===== BUILD TOOL PLUGINS =====
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokkaGradlePlugin" }
spotless-plugin-gradle = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotlessPluginGradle" }
detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detektGradlePlugin" }
org-jlleitschuh-gradle-ktlint-gradle-plugin = { module = "org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin", version.ref = "ktlint" }
openapi-generator-gradle-plugin = { module = "org.openapitools:openapi-generator-gradle-plugin", version.ref = "openapiGeneratorGradlePlugin" }

# ===== DATASTORE =====
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version = "1.1.7" }
datastore-core = { group = "androidx.datastore", name = "datastore-core", version = "1.1.7" }

# ===== TESTING =====
junit4 = { group = "junit", name = "junit", version.ref = "junit" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitJupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitJupiter" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestJunit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
mockk = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

[bundles]
# ===== ANDROID CORE =====
androidx-core = [
    "androidx-core-ktx",
    "androidx-appcompat",
    "androidx-material"
]

# ===== COMPOSE =====
compose = [
    "androidx-compose-ui",
    "androidx-compose-material3",
    "androidx-activity-compose",
    "androidx-navigation-compose",
    "androidx-compose-ui-tooling-preview"
]

# ===== COROUTINES =====
coroutines = [
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-android"
]

# ===== FIREBASE =====
firebase = [
    "firebase-analytics-ktx",
    "firebase-crashlytics-ktx",
    "firebase-perf-ktx"
]

# ===== NETWORKING =====
network = [
    "retrofit",
    "retrofit-converter-kotlinx-serialization",
    "okhttp3-logging-interceptor"
]

# ===== ROOM =====
room = [
    "room-runtime",
    "room-ktx",
]

# ===== TESTING =====
testing = [
    "junit4",
    "junit-jupiter-api",
    "junit-jupiter-engine",
    "mockk",
    "turbine"
]

# ===== LIFECYCLE =====
lifecycle = [
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-viewmodel-ktx",
    "androidx-lifecycle-viewmodel-compose"
]

# ===== XPOSED =====
xposed = [
    "yukihook-api",
    "xposed-api"
]
